version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "America/New_York"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
    groups:
      testing:
        patterns:
          - "*junit*"
          - "*mockito*"
          - "*assertj*"

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "America/New_York"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 10
