/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dev.aga.gradle.plugin.versioncatalogs

import org.gradle.api.Plugin
import org.gradle.api.initialization.Settings

class VersionCatalogGeneratorPlugin : Plugin<Settings> {
    // nothing to do in apply, all our logic
    // is in the extension function
    override fun apply(settings: Settings) {}
}
