
=== Caching
Unfortunately, settings plugins in Gradle cannot take advantage of the same caching mechanisms that are provided
for tasks with incremental builds. However, we have added the ability to save the generated TOML catalog to a file,
and the build will (re)use that file the next time the build is invoked. The behavior is disabled by default, but may
be enabled at a later time.

[source,kotlin,subs="attributes+"]
----
generate("myLibs") {
  // excluded for brevity
  cacheEnabled = true // <1>
  cacheDirectory = file("build/version-catalogs") // <2>
}
----
<1> Enable the caching functionality
<2> The directory to save the generated catalogs in. If not specified, the generated catalogs will be saved in
`build/version-catalogs`, relative to the _root_ project directory.

CAUTION: When enabling caching, be mindful of the cache directory being used. You will mostly likely _want_ to make sure
the directory is cleaned by the `clean` task. If the cache directory is not affected by `clean`, changes to the source
may not be properly recognized and your generated catalog may contain stale data.
