
=== Filtering Dependencies
If you want to exclude certain dependencies from having entries generated for them in your catalog, you can filter
dependencies either by providing a filter or by providing regex patterns
to exclude by `groupId` or by `name` (artifactId)

==== Customizable Filtering
The most flexible and granular way of filtering is by setting a `filter` in the
`UsingConfig`. When this function returns `true` for a dependency it will be
included in the generated catalog. Otherwise, it will be excluded.

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
generate("testLibs") {
  // excluded for brevity
  using { // <1>
    filter = { "testing" in it.artifactId } // <2>
  }
  from {
    // excluded for brevity
    using { // <3>
      filter = "..." // excluded for brevity
    }
  }
}
----
<1> Set the default `filter` for all `from` blocks
<2> Only include dependencies whose `artifactId` contain the word "testing"
<3> Set/override the `filter` for just this from block

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
generator.generate("testLibs") {
  // excluded for brevity
  it.using { using ->  // <1>
    using.filter = { dep -> dep.artifactId.contains("testing") } // <2>
  }
  it.from { from ->
   // excluded for brevity
   from.using { using -> // <3>
     using.filter = { "..." } // excluded for brevity
   }
  }
}
----
<1> Set the default `filter` for all `from` blocks
<2> Only include dependencies whose `artifactId` contain the word "testing"
<3> Set/override the `filter` for just this from block


==== Filtering By GroupId

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
generate("myLibs") {
  // excluded for brevity
  using { // <1>
    excludeGroups = ".*spring.*" // <2>
  }
  from {
    // excluded for brevity
    using { // <3>
      excludeGroups = "..." // excluded for brevity
    }
  }
}
----
<1> Set the default `excludeGroups` for all `from` blocks
<2> Exclude all dependencies that have "spring" in their groupId
<3> Set/override the `excludeGroups` for just this from block

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
generator.generate("myLibs") {
  // excluded for brevity
  it.using { using ->  // <1>
    using.excludeGroups = ".*spring.*" // <2>
  }
  it.from { from ->
   // excluded for brevity
   from.using { using -> // <3>
     using.excludeGroups = "..." // excluded for brevity
   }
  }
}
----
<1> Set the default `excludeGroups` for all `from` blocks
<2> Exclude all dependencies that have "spring" in their groupId
<3> Set/override the `excludeGroups` for just this from block

==== Filtering By Name

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
generate("myLibs") {
  // excluded for brevity
  using { // <1>
      excludeNames = ".*hibernate.*" // <2>
  }
  from {
    // excluded for brevity
    using { // <3>
      excludeNames = "..." // excluded for brevity
    }
  }
}
----
<1> Set the default `excludeNames` for all `from` blocks
<2> Exclude all dependencies that have "hibernate" in their name/artifactId
<3> Set/override the `excludeNames` for just this from block

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
generator.generate("myLibs") {
  // excluded for brevity
  it.using { using -> // <1>
    using.excludeNames = ".*hibernate.*" // <2>
  }
  it.from { from ->
    // excluded for brevity
    from.using { using -> // <3>
      using.excludeNames = "..."
    }
  }
}
----
<1> Set the default `excludeNames` for all `from` blocks
<2> Exclude all dependencies that have "hibernate" in their name/artifactId
<3> Set/override the `excludeNames` for just this from block
