
=== Customizing Library Aliases

The aliases we generate for libraries discovered in the BOM are based on two separate components,
a `prefix` and a `suffix`. The prefix and suffix are separated by a hyphen to create the library's alias.
If the prefix is blank, it will be ignored entirely.

==== Default Behavior
The default algorithm is as follows:

===== Prefix Generation
1. The `groupId` of the dependency is split by `.`
2. If the split only returns a list of one item and the value is the string `bundles`, `plugins`, or `versions`, an
`IllegalArgumentException` is thrown
3. If the split returns a list of two or more items, and the last value is one of the invalid strings listed above, the
last two items in the list are concatenated by a hyphen. The entirety of the string is the converted to camelCase
4. In any other scenario, the last item in the list is returned as-is

NOTE: Due to the popularity of many packages that may not necessarily fit our algorithm, a number of special cases have
been added to simplify their generated prefixes. Please refer to the below table for the hardcoded aliases we have
set up. If you do not wish to use the aliases, you will need to provide your own prefix generation function.

[cols="3*", options="header"]
|===
| Condition         | Value | Generated Prefix
| Group begins with | `androidx` | `androidx`
| Group begins with | `com.fasterxml.jackson` | `jackson`
| Group begins with | `com.facebook` | `facebook`
| Group begins with | `com.google.android` | `android`
| Group begins with | `com.oracle.database` | `oracle`
| Group begins with | `com.squareup.okhttp` | `okhttp`
| Group begins with | `com.squareup.okhttp3` | `okhttp3`
| Group begins with | `com.squareup.retrofit` | `okhttp`
| Group begins with | `com.squareup.retrofit2` | `okhttp3`
| Group begins with | `commons-` | `commons`
| Group begins with | `org.apache.httpcomponents` | `httpcomponents`
| Group begins with | `org.apache.tomcat` | `tomcat`
| Group begins with | `org.eclipse.jetty` | `jetty`
| Group begins with | `org.elasticsearch` | `elasticsearch`
| Group begins with | `org.firebirdsql` | `firebird`
| Group begins with | `org.glassfish.jersey` | `jersey`
| Group begins with | `org.hibernate` | `hibernate`
| Group begins with | `org.jetbrains.kotlin` | `kotlin`
| Group begins with | `org.jetbrains.kotlinx` | `kotlinx`
| Group begins with | `org.junit` | `junit`
| Group begins with | `org.mariadb` | `mariadb`
| Group begins with | `org.mockito` | `mockito`
| Group begins with | `org.neo4j` | `neo4j`
| Group begins with | `org.spockframework` | `spock`
| Group begins with | `org.springframework` | `spring`
| Group begins with | `io.dropwizard` | `dropwizard`
| Group begins with | `io.projectreactor` | `projectreactor`
| Group begins with | `io.zipkin` | `zipkin`
| Group begins with | `jakarta.` | `jakarta`
| Group begins with | `javax.` | `javax`
| Group begins with | `tools.jackson` | `jackson3`
|===

===== Suffix Generation
1. Replace any `.` or `_` character in the `artifactId` of the dependency with a `-`
2. Convert the resulting string to camelCase

===== Examples
* `org.springframework.boot:spring-boot-starter-web` -> `spring-springBootStarterWeb`
* `com.fasterxml.jackson.core:jackson-databind` -> `jackson-jacksonDatabind`
* `com.fasterxml.jackson.datatype:jackson-datatype-jsr310` -> `jackson-jacksonDatatypeJsr310`
* `software.amazon.awssdk:s3` -> `awssdk-s3`
* `org.hibernate.orm:hibernate-core` -> `orm.hibernateCore`

TIP: In some cases our default logic may not be sufficient and it may attempt to store two dependencies with the same
alias. If this happens, an exception will be thrown pointing to the errant dependencies and you will either need to
exclude one or more of the conflicting dependencies, or override the default behavior. `spring-boot-dependencies` in the 2.7.x
version range is known to cause problems due to conflicting entries of `ehcache`. See https://github.com/austinarbor/version-catalog-generator/issues/100[#100]

==== Customizing Prefix Generation
The prefix generation logic can be modified by overriding the property `aliasPrefixGenerator` in `GeneratorConfig`

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
generate("myLibs") {
  // excluded for brevity
  using { // <1>
    aliasPrefixGenerator = { groupId, artifactId ->
     if(groupId == "some.group") {
         "somegroup"
     } else {
         GeneratorConfig.DEFAULT_ALIAS_PREFIX_GENERATOR(groupId, artifactId) // <2>
     }
    }
  }
  from {
    // excluded for brevity
    using {
      aliasPrefixGenerator = GeneratorConfig.DEFAULT_ALIAS_PREFIX_GENERATOR // <3>
    }
  }
}
----
<1> Set the default `aliasPrefixGenerator` for all `from` blocks
<2> We can always fall back to the default logic if our condition isn't met
<3> Set/override the `aliasPrefixGenerator` for just this `from` block

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
generator.generate("myLibs") {
  // excluded for brevity
  it.using { using -> // <1>
    using.aliasPrefixGenerator = { groupId, artifactId ->
      if(groupId == "some.group") {
        "somegroup"
      } else {
      DEFAULT_ALIAS_PREFIX_GENERATOR.invoke(groupId, artifactId) // <2>
      }
    }
  }
  it.from { from ->
    // excluded for brevity
   from.using { using ->
     using.aliasPrefixGenerator = DEFAULT_ALIAS_PREFIX_GENERATOR // <3>
   }
  }
}
----
<1> Set the default `aliasPrefixGenerator` for all `from` blocks
<2> We can always fall back to the default logic if our condition isn't met
<3> Set/override the `aliasPrefixGenerator` for just this `from` block

===== Skipping Prefix Generation Entirely
In some BOMs which _only_ contain their own dependencies, for example the AWS BOM, the inclusion of the prefix may
not be useful and instead you may want to skip the prefix entirely. A convenience function is provided to do so.

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
generate("awsLibs") {
  fromToml("awsBom") {
    aliasPrefixGenerator = GeneratorConfig.NO_PREFIX // <1>
  }
}
----
<1> The resulting generated alias for `software.amazon.awssdk:s3` would just be `s3`. When accessing this library
in our build file, the accessor would subsequently be `awsLibs.s3` instead of `awsLibs.awssdk.s3`

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
generator.generate("awsLibs") {
  it.fromToml("awsBom")
  it.using { using ->
    using.aliasPrefixGenerator = NO_PREFIX // <1>
  }
}
----
<1> The resulting generated alias for `software.amazon.awssdk:s3` would just be `s3`. When accessing this library
in our build file, the accessor would subsequently be `awsLibs.s3` instead of `awsLibs.awssdk.s3`

==== Customizing Suffix Generation
The suffix generation logic can be modified by overriding the property `aliasSuffixGenerator` in `GeneratorConfig`

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
generate("myLibs") {
  // excluded for brevity
  using { // <1>
    aliasSuffixGenerator = { prefix, groupId, artifactId -> // <2>
     val suffix = GeneratorConfig.DEFAULT_ALIAS_SUFFIX_GENERATOR(groupId, artifactId) // <3>
     if(prefix == "spring") {
       suffix.replaceFirst("spring","") // <4>
     } else {
       suffix
     }
    }
  }
  from {
    // excluded for brevity
    using {
      aliasSuffixGenerator = GeneratorConfig.DEFAULT_ALIAS_SUFFIX_GENERATOR // <5>
    }
  }
}
----
<1> Set the default `aliasSuffixGenerator` for all `from` blocks
<2> The prefix argument refers to the generated prefix value for the dependency
<3> The default logic can always be accessed through `GeneratorConfig.DEFAULT_ALIAS_SUFFIX_GENERATOR`
<4> In this example we are extending the default behavior to remove the "duplicate" appearance of the word `spring`.
For example, instead of `spring-springBootStarterWeb`, we would generate `spring-bootStarterWeb`
<5> Set/override the `aliasSuffixGenerator` for just this `from` block

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
generator.generate("myLibs") {
  // excluded for brevity
  it.using { using -> // <1>
    using.aliasSuffixGenerator = { prefix, groupId, artifactId -> // <2>
     def suffix = DEFAULT_ALIAS_SUFFIX_GENERATOR.invoke(groupId, artifactId) // <3>
     if(prefix == "spring") {
         suffix.replaceFirst("spring","") // <4>
     } else {
         suffix
     }
    }
  }
  it.from { from ->
    from.using { using ->
      using.aliasSuffixGenerator = DEFAULT_ALIAS_SUFFIX_GENERATOR // <5>
    }
  }
}
----
<1> Set the default `aliasSuffixGenerator` for all `from` blocks
<2> The prefix argument refers to the generated prefix value for the dependency
<3> The default logic can always be accessed through `DEFAULT_ALIAS_SUFFIX_GENERATOR`
<4> In this example we are extending the default behavior to remove the "duplicate" appearance of the word `spring`.
For example, instead of `spring-springBootStarterWeb`, we would generate `spring-bootStarterWeb`
<5> Set/override the `aliasSuffixGenerator` for just this `from` block

=== Customizing Version Aliases
If any dependencies in the source BOM specify a dependency's version via a property, we will create a version alias in
the generated catalog for that behavior.

==== Default Behavior
The default algorithm to generate a version alias from a property is:

1. Replace all case-insensitive instances of the literal string `version` with an empty string
2. All instances of two or more consecutive periods are replaced with a single period
3. Any leading or trailing periods are trimmed
4. All periods are replaced with a hyphen
5. The entire string is converted to camelCase

===== Examples
* `jackson.version` -> `jackson`
* `version.jackson` -> `jackson`
* `jackson.modules.version` -> `jacksonModules`

==== Customizing Version Aliases
The version alias generation logic can be customized by overriding the property `versionNameGenerator` in `GeneratorConfig`

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
generate("myLibs") {
  // excluded for brevity
  using { // <1>
    versionNameGenerator = { propertyName -> // <2>
     if(propertyName == "somethingWeird") {
         "notAsWeird"
     } else {
         GeneratorConfig.DEFAULT_VERSION_NAME_GENERATOR(propertyName) // <3>
     }
    }
  }
  from {
    // excluded for brevity
    using {
      versionNameGenerator = GeneratorConfig.DEFAULT_VERSION_NAME_GENERATOR // <4>
    }
  }
}
----
<1> Set the default `versionNameGenerator` for all `from` blocks
<2> The property name from the maven POM, i.e. `jackson.version`
<3> The default logic can always be accessed through `GeneratorConfig.DEFAULT_VERSION_NAME_GENERATOR`
<4> Set/override the `versionNameGenerator` for just this `from` block

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
generator.generate("myLibs") {
  // excluded for brevity
  it.using { using -> // <1>
    using.versionNameGenerator = { propertyName -> // <2>
     if(propertyName == "somethingWeird") {
         "notAsWeird"
     } else {
         DEFAULT_VERSION_NAME_GENERATOR.invoke(propertyName) // <3>
     }
    }
  }
  it.from { from ->
    // excluded for brevity
    from.using { using ->
      using.versionNameGenerator = DEFAULT_VERSION_NAME_GENERATOR // <4>
    }
  }
}
----
<1> Set the default `versionNameGenerator` for all `from` blocks
<2> The property name from the maven POM, i.e. `jackson.version`
<3> The default logic can always be accessed through `DEFAULT_VERSION_NAME_GENERATOR`
<4> Set/override the `versionNameGenerator` for just this `from` block

=== Customizing Bundle Generation
In addition to generating libraries, you can also customize how bundles are generated by providing a custom function
to the `GeneratorConfig`. The mapping is run after all libraries have been generated for the entire catalog. The default
behavior is to map a dependency to a bundle if and only if the version for that dependency is a `versionRef`, and
the name of the bundle will be the `versionRef` itself.

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
generator.generate("myLibs") {
  bundleMapping = {
    if(it.group.contains("junit")) {
      "junit" // <1>
    } else {
      null // <2>
    }
  }
}
----
<1> Map all dependencies with a `group` containing `junit` into a bundle called `junit`
<2> Dependencies mapped to `null` or a blank string will be ignored

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
generator.generate("myLibs") {
  it.bundleMapping = { lib ->
    if(lib.group.contains("junit")) {
      "junit" // <1>
    } else {
      null // <2>
    }
  }
}
----
<1> You will have to add an import for net.pearx.kasechange.CaseFormat into the build file. The dependency
is already available for use when you apply the plugin

TIP: If you are appending to an existing catalog, you can create bundles that contain dependencies from both original
catalog and the BOM(s) you are generating from.

=== Case Conversion
For converting between different text cases, for example lower-hyphen to lower-camel, you can use the convenience
function `caseChange`

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
aliasSuffixGenerator = { _, _, artifactId ->
    GeneratorConfig.caseChange(artifactId, CaseFormat.LOWER_HYPEN, CaseFormat.CAMEL) // <1>
}
----
<1> You will have to add an import for net.pearx.kasechange.CaseFormat into the build file. The dependency
is already available for use when you apply the plugin

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
using.aliasSuffixGenerator = { _, _, artifactId ->
    caseChange(artifactId, CaseFormat.LOWER_HYPEN, CaseFormat.CAMEL) // <1>
}
----
<1> You will have to add an import for net.pearx.kasechange.CaseFormat into the build file. The dependency
is already available for use when you apply the plugin
