
=== Overriding Versions
:fn-gradle-overrides: footnote:[You can always use standard Gradle mechanisms such as resolution strategies or platforms if a property is not used to specify the version]
In some cases you may want to override the version specified by the BOM you are generating
the catalog from. At the current point in time, this is only possible if the BOM uses a property
to specify the version{fn-gradle-overrides}

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
generate("myLibs") {
  // excluded for brevity
  using {
    propertyOverrides = mapOf(
      "jackson.version" to "2.16.1", // <1>
      "aws.version" to versionRef("aws") // <2>
    )
  }
}
----
<1> Specify a string version to use in place of all occurrences of `jackson.version` when processing the BOM
<2> Specify an existing version alias from your `defaultVersionCatalog` file. The version alias being
referenced _must_ exist in TOML file.

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
generator.generate("myLibs") {
  // excluded for brevity
  it.using { using ->
    using.propertyOverrides = [
      "jackson.version": "2.16.1", // <1>
      "aws.version": it.versionRef("aws") // <2>
    ]
  }
}
----
<1> Specify a string version to use in place of all occurrences of `jackson.version` when processing the BOM
<2> Specify an existing version alias from your `defaultVersionCatalog` file. The version alias being
referenced _must_ exist in TOML file.
