
=== Dependency Sources

==== TOML

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
dependencyResolutionmanagement {
  versionCatalogs {
    generate("springLibs") {
      from {
        toml {
          libraryAliases = listOf("springBootDependencies") // <1>
          file = file("gradle/libs.versions.toml") // <2>
        }
      }
    }
    generate("awsLibs") {
      fromToml("awsBom") { // <3>
        // excluded for brevity // <4>
      }
    }
    generate("junitLibs") {
      from {
        toml {
          libraryAliases = listOf("boms-junit5")
          file = artifact("io.micronaut.platform:micronaut-platform:4.3.6") // <5>
        }
      }
    }
  }
}
----
<1> Required, the one or more aliases of BOMs to use from the TOML file
<2> The TOML file to find the provided alias in. This only needs to be provided if _not_ using the `defaultVersionCatalog` file
<3> When using the default file, you can use the convenience function `fromToml(..)` and just provide the alias name(s)
<4> Additional configuration options for the generated sources can be passed in a trailing lambda block
<5> If your TOML is published to a repository, you can fetch it using the `artifact` function and standard string
notation.

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
dependencyResolutionmanagement {
  versionCatalogs {
    generator.generate("springLibs") {
      it.from { from ->
        from.toml { toml ->
          toml.libraryAliases = ["springBootDependencies"] // <1>
          toml.file = file("gradle/libs.versions.toml") // <2>
        }
      }
    }
    generator.generate("awsLibs") {
      it.fromToml("spring-boot-dependencies") // <3>
    }
    generate("junitLibs") {
      it.from { from ->
        from.toml { toml ->
          toml.libraryAliases = ["boms-junit5"]
          toml.file = toml.artifact("io.micronaut.platform:micronaut-platform:4.3.6") // <4>
        }
      }
    }
  }
}
----
<1> Required, the one or more aliases of BOMs to use from the TOML file
<2> The TOML file to find the provided alias in. This only needs to be provided if _not_ using the `defaultVersionCatalog` file
<3> When using the default file, you can use the convenience function `fromToml(..)` and just provide the alias name(s)
<4> If your TOML is published to a repository, you can fetch it using the `artifact` function and standard string
notation.

TIP: GitHub's Dependabot only supports automatic updates in the default version catalog `gradle/libs.versions.toml`

==== String Notation

.settings.gradle.kts
[source,kotlin,subs="attributes+",role="primary"]
----
dependencyResolutionmanagement {
  versionCatalogs {
    generate("springLibs") {
      from {
        dependency("org.springframework.boot:spring-boot-dependencies:3.1.2") // <1>
      }
    }
    generate("awsLibs") {
      from("software.amazon.awssdk:bom:2.25.6") { // <2>
        // excluded for brevity // <3>
      }
    }
  }
}
----
<1> You can also use the standard string notation to specify your dependency
<2> More conveniently, you can pass the string notation directly into `from()`. More than one dependency strings can be passed in.
<3> Additional configuration options for the generated sources can be passed in a trailing lambda block

.settings.gradle
[source,groovy,subs="attributes+",role="secondary"]
----
dependencyResolutionmanagement {
  versionCatalogs {
    generator.generate("springLibs") {
      it.from { from ->
        from.dependency("org.springframework.boot:spring-boot-dependencies:3.1.2") // <1>
      }
    }
    generator.generate("awsLibs") {
      it.from("software.amazon.awssdk:bom:2.25.6") // <2>
    }
  }
}
----
<1> You can also use the standard string notation to specify your dependency
<2> More conveniently, you can pass the string notation directly into `from()`. More than one dependency strings can be passed in.

NOTE: Groovy is not my strong point so it's likely that there is simpler / better syntax I'm not aware of. If you have
any suggestions to improve the syntax in the documentation please open an issue or a PR.
